### ISSUE TITLE
Uncaught ReferenceError: seedrandom is not defined / Uncaught ReferenceError: assignment to undeclared variable seedrandom

### ISSUE THREAD

**Issue by JeffreyArts** [webcaetano/shuffle-seed#8]
I get this error when running the following line of code in my (Vue3) environment;

`shuffleSeed.shuffle([1,2,3,4], "a")`

I believe that the solution is rather straightforward, just declare 'seedrandom' by declaring it with a 'var', 'let' or 'const', somewhere on line 3 or 4 🙂

if(Math.seedrandom) seedrandom = Math.seedrandom;

⬇️

if(Math.seedrandom) var seedrandom = Math.seedrandom;

Or am I missing something?

**Comment by JeffreyArts** [comment]
Just so you know, declaring the variable resolves the issue. Without it, it won't be possible to use this module  in a strict environment.

**Comment by 50l3r** [comment]
I think that this change it doesnt uploaded to npm
